name: Deploy to GitHub Pages

on:
  push:
    branches:
      - hugo

jobs:
  deploy:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0 # Fetch all history for .GitInfo and .Lastmod .

      - name: Build Link Index
        uses: jackyzha0/hugo-obsidian@v2.18
        with:
          index: true
          input: content
          output: assets/indices
          root: .

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: "0.96.0"
          extended: true

      - name: Build
        run: hugo --minify
        continue-on-error: true

      - name: push to the garden
        uses: peaceiris/actions-gh-pages@v3
        with:
          publish_dir: ./public
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: commit and push changes
        run: |
          git config --global user.email "anas.swalha@yahoo.co,"
          git config --global user.name "Anas Sawalha"
          git add .
          git commit -m "New publish"
          git push
