name: Deploy to Another Github Repo

on:
  push:
    branches:
      - hugo

jobs:
  deploy:
    runs-on: ubuntu-20.04
    steps:
      - name: fetch
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 # Fetch all history for .GitInfo and .Lastmod

      - name: Build Link Index
        uses: jackyzha0/hugo-obsidian@v2.18
        with:
          index: true
          input: content
          output: assets/indices
          root: .

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: "0.96.0"
          extended: true

      - name: Build
        run: hugo --minify -d public

      - name: Clone Another Github Repo
        uses: actions/checkout@v3
        with:
          path: dest
          ref: main
          repository: anassawalha95/garden
          token: ${{ secrets.DEPLOY_TOKEN }}
          persist-credentials: true
          fetch-depth: 0

      - name: Copy and cleanup Public Folder to Another Github Repo
        shell: bash
        run: |
          rm -rf dest/* && ls dest && echo "line 1"
          ls  && echo "line 2"
          ls public && echo "line 3"
          ls public/indices && echo "line 4"
          cp -r public/* dest && echo "line 5"
          ls dest/indices && echo "line 6"

      - name: Commit and Push to Another Github Repo
        working-directory: dest
        run: |
          git config --global user.email "anas.swalha@yahoo.com"
          git config --global user.name "anassawalha95"
          git add .
          git commit -m "Deploy to Github Pages"
          git push
